// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApiPlayground.Migrations
{
    [DbContext(typeof(ProductDb))]
    [Migration("20230128190524_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("WeightInKg")
                        .HasColumnType("real");

                    b.Property<int?>("DepthInCm")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightInCm")
                        .HasColumnType("int");

                    b.Property<int>("PricePer100")
                        .HasColumnType("int");

                    b.Property<int?>("WidthInCm")
                        .HasColumnType("int");

                    b.HasKey("Name", "WeightInKg");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
